executors:
  node:
    docker:
      - image: circleci/node:13.5.0

aliases:
  restore_cache: &restore_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

  install_node_modules: &install_node_modules
    run:
      name: Install Dependencies
      command: sudo yarn install --frozen-lockfile

  save_cache: &save_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-{{ checksum "yarn.lock" }}
      paths:
        - ~/.cache/yarn

version: 2.1

jobs:
  test:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - <<: *save_cache
      - run:
          name: Test
          command: yarn lint

  build:
    executor: node
    steps:
      - checkout
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Install gatsby
          command: sudo yarn global add gatsby
      - run:
          name: Build
          command: gatsby build
      - persist_to_workspace:
          root: ./
          paths:
            - public

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *restore_cache
      - <<: *install_node_modules
      - run:
          name: Install netlify-cli
          command: sudo yarn global add netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./public -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
